services:
  mongodb_blog5:
    image: mongo:latest
    container_name: mongodb_blog5
    environment:
      # 从 .env 文件加载环境变量
      # 这里的配置只有首次运行生效。修改后，重启镜像是不会生效的。需要把持久化数据删除再重启，才有效果
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      # 将 MongoDB 数据文件夹挂载到宿主机
      - ./data:/data/db
    networks:
      - mongo_network
    restart: always

networks:
  mongo_network:
    driver: bridge
